export interface GuideSection {
  id: string;
  title: string;
  text: string;
  steps: string[];
  warning?: string;
  adminOnly?: boolean;
}

export const guideSections: GuideSection[] = [
  {
    id: "accesso",
    title: "Accesso, sicurezza e cambio password",
    text: "Lo username del gestionale non è un indirizzo email. I permessi dipendono dal ruolo assegnato all'account.",
    steps: [
      "Accedi con username e password assegnati.",
      "Al primo accesso scegli una nuova password e ripetila.",
      "Un Capo Area vede e gestisce soltanto le aree assegnate; Amministrazione ha visione globale.",
      "Se hai dimenticato la password contatta Amministrazione: non usare l'indirizzo Auth interno come normale email.",
    ],
    warning: "Non condividere password, token o link privati in spazi pubblici.",
  },
  {
    id: "disponibilita",
    title: "Trovare e prendere una disponibilità",
    text: "Disponibilità mostra giornate, aule, note e capacità simultanea aperte dall'Amministrazione.",
    steps: [
      "Apri Disponibilità e filtra per data o aula.",
      "Attiva Posti liberi per l'intera fascia se vuoi vedere solo finestre con capacità residua per tutto l'intervallo.",
      "Premi Seleziona sulla disponibilità desiderata e scegli area e recruitment.",
      "Restringi inizio e fine dentro i limiti della finestra e verifica l'indicatore di capacità prima di confermare.",
    ],
    warning: "Una finestra apparentemente completa può avere una sottofascia libera: prova un intervallo più breve senza il filtro Posti liberi per l'intera fascia.",
  },
  {
    id: "capacita",
    title: "Capire capacità e contemporaneità",
    text: "Il primo numero indica l'uso contemporaneo già assegnato; il secondo la capacità della finestra.",
    steps: [
      "0/2 significa due postazioni ancora disponibili.",
      "1/2 significa che rimane una postazione contemporanea.",
      "2/2 significa capacità raggiunta nell'intervallo considerato.",
      "09:00–10:00 e 10:00–11:00 sono consecutivi e non si sovrappongono.",
    ],
  },
  {
    id: "assegnazioni",
    title: "Restituire una fascia assegnata",
    text: "Il Capo Area può restituire un intervallo oppure tutta la fascia, rendendo la capacità nuovamente disponibile.",
    steps: [
      "Nella sezione Le mie assegnazioni imposta Da e A se vuoi restituire solo una parte.",
      "Per un intervallo parziale usa Rilascia intervallo.",
      "Per l'intera fascia usa Rilascia / annulla tutto e scegli se conservarne lo storico oppure eliminarla definitivamente.",
      "Dopo il rilascio la capacità torna utilizzabile dalle altre aree.",
    ],
    warning: "L'eliminazione definitiva rimuove anche la sessione e i dati di scheduling collegati e non è recuperabile.",
  },
  {
    id: "sessioni",
    title: "Creare una sessione e generare slot",
    text: "Una sessione usa una fascia assegnata alla tua area.",
    steps: [
      "Apri Sessioni e slot.",
      "Scegli la fascia, inserisci un nome riconoscibile e la durata in minuti.",
      "Premi Crea e genera slot.",
      "Apri Gestisci per verificare tutti gli orari generati e il loro stato.",
    ],
  },
  {
    id: "slot",
    title: "Gestire gli slot",
    text: "Gli slot liberi possono essere modificati, chiusi, riaperti o eliminati; gli appuntamenti confermati si gestiscono dal Calendario.",
    steps: [
      "Apri Gestisci nella riga della sessione.",
      "Su uno slot libero usa Modifica orario per cambiare inizio e fine dentro la fascia assegnata.",
      "Chiudi slot lo rende non prenotabile; Riapri lo rende nuovamente prenotabile quando la sessione lo consente.",
      "Elimina definitivamente rimuove lo slot e l'eventuale storico annullato collegato, se non esiste una prenotazione confermata.",
    ],
    warning: "Un appuntamento confermato deve prima essere spostato, annullato o eliminato dal Calendario.",
  },
  {
    id: "sessione-chiudi-annulla",
    title: "Chiudere, annullare o eliminare una sessione",
    text: "Chiudi sessione e Annulla sessione hanno effetti diversi.",
    steps: [
      "Chiudi sessione revoca il link e chiude gli slot liberi, ma lascia confermate le prenotazioni esistenti.",
      "Annulla sessione apre una scelta: Annulla e conserva oppure Annulla ed elimina definitivamente.",
      "Annulla e conserva annulla le prenotazioni confermate, chiude gli slot, libera la fascia dell'area e mantiene lo storico.",
      "Annulla ed elimina definitivamente rimuove sessione, slot, prenotazioni e dati di scheduling collegati senza possibilità di recupero.",
    ],
    warning: "Usa l'eliminazione definitiva solo quando vuoi davvero perdere lo storico della sessione e dei relativi appuntamenti.",
  },
  {
    id: "link",
    title: "Link candidato dell'area",
    text: "Ogni area usa il proprio link pubblico stabile di prenotazione; il candidato non deve creare un account.",
    steps: [
      "Apri Sessioni e slot e usa il link dell'area associata.",
      "Il link raccoglie gli slot pubblicabili e liberi dell'area nelle diverse giornate e aule.",
      "Revocando o chiudendo le risorse collegate gli slot non più validi scompaiono dal link pubblico.",
      "Condividi il link soltanto con i candidati interessati.",
    ],
  },
  {
    id: "candidato",
    title: "Come prenota il candidato",
    text: "Per inviare una prenotazione servono i dati richiesti, l'email @studenti.unipi.it e l'accettazione obbligatoria dell'informativa privacy corrente.",
    steps: [
      "Il candidato apre il link della propria area e sceglie uno slot libero.",
      "Inserisce nome, cognome ed email universitaria @studenti.unipi.it.",
      "Apre e legge l'Informativa privacy visualizzata nel modulo.",
      "Spunta l'accettazione obbligatoria dell'informativa e del trattamento dei dati personali.",
      "Conferma la prenotazione e controlla il riepilogo a schermo, quindi Posta in arrivo e Spam per l'email di conferma.",
    ],
    warning: "La prenotazione è rifiutata anche lato server se manca il consenso oppure se nel frattempo l'Amministrazione ha pubblicato una versione più recente dell'informativa.",
  },
  {
    id: "privacy-consenso",
    title: "Come viene registrato il consenso privacy",
    text: "GalileoHub registra insieme alla prenotazione la versione dell'informativa accettata e il momento dell'accettazione.",
    steps: [
      "La checkbox non è preselezionata e deve essere accettata espressamente dal candidato.",
      "Il server verifica che la versione mostrata al candidato sia ancora quella corrente.",
      "Se l'informativa cambia prima dell'invio, il candidato deve rileggere e accettare la nuova versione.",
      "L'accettazione è collegata alla prenotazione e segue il suo ciclo di vita: se la prenotazione viene eliminata definitivamente, viene eliminata anche la relativa registrazione di consenso.",
    ],
  },
  {
    id: "calendario",
    title: "Leggere il Calendario: prenotati, liberi e annullati",
    text: "Lista e vista settimanale mostrano nello stesso punto gli appuntamenti e gli slot ancora disponibili della propria area; Amministrazione può vedere tutte le aree.",
    steps: [
      "Usa la legenda in alto: Prenotati, Liberi e Annullati nello storico hanno indicazioni visive separate.",
      "Cambia settimana con le frecce, Oggi oppure scegliendo una data.",
      "In Lista ogni riga indica orario, area, aula, candidato oppure Slot libero e sessione.",
      "Nella vista Calendario l'altezza del blocco segue la durata reale. Su telefono puoi scorrere orizzontalmente o usare Lista.",
      "Clicca un elemento per aprire le operazioni consentite.",
    ],
  },
  {
    id: "sposta",
    title: "Spostare una prenotazione",
    text: "Il Capo Area può spostare una prenotazione soltanto verso slot compatibili che può gestire; Amministrazione opera globalmente secondo le regole della campagna.",
    steps: [
      "Apri la prenotazione dal Calendario.",
      "Scegli uno slot libero proposto.",
      "Premi Conferma spostamento.",
      "Il vecchio slot torna libero e viene preparata la notifica email con i nuovi dettagli.",
    ],
    warning: "Se lo slot viene occupato nel frattempo, lo spostamento viene rifiutato per evitare doppie prenotazioni.",
  },
  {
    id: "annulla",
    title: "Annullare oppure annullare ed eliminare una prenotazione",
    text: "Quando premi Annulla prenotazione GalileoHub ti chiede esplicitamente quale delle due operazioni vuoi eseguire.",
    steps: [
      "Annulla e conserva: lo stato diventa Annullato, la prenotazione resta visibile nello storico e lo slot torna immediatamente libero e prenotabile.",
      "Annulla ed elimina definitivamente: la prenotazione viene rimossa dal database insieme ai dati strettamente collegati previsti dall'operazione e non è recuperabile.",
      "Una prenotazione già annullata e conservata può essere eliminata definitivamente in un secondo momento.",
      "Dopo entrambe le operazioni lo slot può essere nuovamente prenotato se la sessione e la fascia sono ancora attive.",
    ],
    warning: "L'eliminazione definitiva è irreversibile. Se vuoi mantenere traccia dell'accaduto, usa Annulla e conserva.",
  },
  {
    id: "bacheca",
    title: "Leggere la Bacheca",
    text: "Il badge indica i messaggi non letti della tua area.",
    steps: [
      "Apri Bacheca dal menu.",
      "Leggi i messaggi importanti e in evidenza.",
      "Segna come letto dopo aver preso visione.",
      "Le comunicazioni scadute non vengono più mostrate ai Capi Area.",
    ],
  },
  {
    id: "problemi",
    title: "FAQ e problemi comuni",
    text: "Prima di ripetere un'operazione aggiorna la pagina o i dati per verificare se è già riuscita.",
    steps: [
      "Nessuna fascia? Verifica data, filtri, recruitment attivo e disponibilità aperte.",
      "Aula piena? Prova una sottofascia diversa e controlla la capacità aggiornata.",
      "Link non valido? Verifica che l'area e le relative sessioni siano attive.",
      "Email non arrivata? Controlla Spam e chiedi ad Amministrazione di verificare Diagnostica email.",
      "Privacy non disponibile o aggiornata? Ricarica la pagina e usa la versione corrente prima di prenotare.",
      "Errore persistente? Comunica ad Amministrazione schermata, operazione e orario, senza inviare password o token.",
    ],
  },
  {
    id: "admin-campagne",
    title: "Creare, modificare e archiviare recruitment",
    adminOnly: true,
    text: "Una nuova campagna nasce come bozza e viene resa operativa solo quando viene attivata.",
    steps: [
      "Apri Recruitment e inserisci nome e date.",
      "Crea la bozza e attivala quando deve essere utilizzabile dalle aree.",
      "Usa Modifica / Gestisci per cambiare nome, date o stato nel rispetto delle fasce già collegate.",
      "Archivia quando termina il recruitment.",
    ],
  },
  {
    id: "admin-aule",
    title: "Aule, disponibilità e cancellazione",
    adminOnly: true,
    text: "Amministrazione definisce il limite fisico dell'aula e le finestre operative nelle singole giornate.",
    steps: [
      "Crea l'aula e imposta l'eventuale limite fisico di colloqui simultanei.",
      "Apri una o più disponibilità giornaliere indicando orari, capacità e nota per le aree.",
      "Modifica cambia orari, capacità e nota senza poter escludere assegnazioni esistenti o scendere sotto l'utilizzo corrente.",
      "Annulla apre la scelta tra conservare la disponibilità nello storico oppure eliminarla definitivamente insieme ai dati di scheduling collegati.",
    ],
    warning: "Eliminare definitivamente una disponibilità con dati collegati rimuove anche assegnazioni, sessioni, slot e prenotazioni appartenenti a quella disponibilità.",
  },
  {
    id: "admin-periodo",
    title: "Aprire un giorno o un periodo di più giorni",
    adminOnly: true,
    text: "Il modulo giornaliero crea finestre separate per ciascuna data selezionata.",
    steps: [
      "Scegli aula, data iniziale e finale, ora di inizio e fine e giorni della settimana.",
      "Inserisci capacità e nota.",
      "Controlla l'anteprima delle date che verranno create.",
      "Conferma: le giornate create insieme condividono lo stesso identificativo di gruppo.",
    ],
    warning: "Se una giornata si sovrappone a una disponibilità già esistente, il gruppo viene rifiutato per evitare inserimenti incoerenti.",
  },
  {
    id: "admin-online",
    title: "Vedere quali Capi Area sono online",
    adminOnly: true,
    text: "La Dashboard Amministrazione mostra il numero e i nomi dei Capi Area attivi nel gestionale negli ultimi 90 secondi.",
    steps: [
      "Apri Dashboard come Amministrazione.",
      "Controlla la scheda Capi Area online per il conteggio corrente.",
      "Nel riquadro dedicato trovi nome e area di ciascun Capo Area online.",
      "La presenza si aggiorna automaticamente circa ogni 30 secondi e viene marcata offline al logout esplicito.",
    ],
    warning: "La presenza indica attività recente nel gestionale, non certifica che la persona stia guardando lo schermo in quell'esatto secondo.",
  },
  {
    id: "admin-legal",
    title: "Modificare Termini di Servizio e Privacy",
    adminOnly: true,
    text: "La pagina Termini e Privacy permette all'Amministrazione di leggere e aggiornare i due testi ufficiali in qualsiasi momento.",
    steps: [
      "Apri Termini e Privacy dal menu Amministrazione.",
      "Scegli Informativa Privacy oppure Termini di Servizio.",
      "Modifica titolo e testo e salva la nuova versione.",
      "Ogni salvataggio incrementa la versione del documento.",
      "La nuova versione Privacy diventa quella che il candidato deve accettare obbligatoriamente nelle prenotazioni successive.",
    ],
    warning: "Il gestionale applica tecnicamente il testo salvato. La correttezza giuridica del contenuto resta responsabilità dell'Amministrazione che lo approva e lo modifica.",
  },
  {
    id: "admin-account",
    title: "Gestire account e ruoli",
    adminOnly: true,
    text: "Gli account sono separati dai dati di prenotazione e di scheduling.",
    steps: [
      "Crea l'account con username, nome visualizzato, ruolo e area.",
      "Comunica la password temporanea tramite un canale sicuro.",
      "Modifica / Gestisci permette di cambiare username, nome, ruolo, area e stato.",
      "Disattiva un account senza cancellarne lo storico; deve rimanere almeno un amministratore attivo.",
    ],
    warning: "Le operazioni di pulizia di prenotazioni, slot, giornate o recruitment non devono essere usate per gestire gli account e non li resettano.",
  },
  {
    id: "admin-calendario",
    title: "Calendario generale e filtro area",
    adminOnly: true,
    text: "Amministrazione vede appuntamenti confermati, annullati conservati e slot liberi di tutte le aree.",
    steps: [
      "Lascia Tutte le aree per il quadro generale oppure seleziona un'area.",
      "Usa la legenda per distinguere Prenotati, Liberi e Annullati nello storico.",
      "Apri una prenotazione per spostarla, annullarla mantenendo lo storico o eliminarla definitivamente.",
      "Apri uno slot libero per modificarne l'orario, chiuderlo o eliminarlo definitivamente.",
    ],
  },
  {
    id: "admin-email",
    title: "Testare email e diagnosticare consegne",
    adminOnly: true,
    text: "Una risposta positiva del provider significa accettazione del messaggio, non prova assoluta della ricezione nella casella.",
    steps: [
      "Configura il provider email soltanto nei secret server, mai nelle variabili pubbliche Vite.",
      "Invia un'email di prova a una casella che puoi controllare e verifica anche Spam.",
      "In Diagnostica email: pending = in coda, sending = in corso, sent = accettata dal provider, failed = errore.",
      "Dopo aver corretto un problema usa Riprova sulle consegne fallite.",
    ],
  },
];
