export const membershipTerms = [
  "In tale sede si impegna a:",
  "Rispettare le norme di sicurezza e comportamento prescritte nei regolamenti di Ateneo ed elaborati tecnici (misure di emergenza, uso spazi operativi e procedure interne del Team Galileo);",
  "Rispettare le disponibilità dichiarate, le scadenze operative, la comunicazione interna (consultazione quotidiana dei canali di lavoro) e aggiornare costantemente il Teams sullo stato d'avanzamento dei progetti;",
  "Rispettare i vincoli gestionali ed economico-patrimoniali, ottenendo preventiva autorizzazione scritta (Team Leader/Faculty Advisor) per ogni spesa o impegno finanziario, e astenendosi dall'asportare materiali o componenti dell'Ateneo;",
  "Utilizzare le risorse informatiche (account, cloud, licenze software) con diligenza, riservatezza ed esclusivamente per fini istituzionali correlati ai progetti del Team;",
  "Tutelare l'immagine del Team, previa autorizzazione della Communication Area prima della diffusione di materiali o contenuti digitali, e indossando il vestiario ufficiale esclusivamente in contesti autorizzati;",
  "Seguire la procedura corretta in caso di recesso, garantendo la riconsegna di beni/licenze, l'affiancamento del subentrante e la consegna della documentazione tecnica.",
  "1. Accettazione del Regolamento Interno",
  "Dichiara di aver preso visione del Regolamento Interno del Team Galileo e di accettarne integralmente ogni disposizione, compresi i criteri di merito per la permanenza e le relative procedure di decadenza.",
  "2. Proprietà Intellettuale e responsabilità",
  "Riconosce che ogni prodotto dell’ingegno, codice, modello o dato sviluppato nell’ambito del Team è di esclusiva proprietà dell’Università di Pisa. Il sottoscritto solleva il Team, l’Ateneo e il Faculty Advisor da qualsiasi responsabilità civile o penale derivante da proprie condotte improprie o violazioni dei protocolli.",
  "3. Autocertificazione Requisiti",
  "Consapevole delle sanzioni previste per dichiarazioni mendaci, dichiara sotto la propria responsabilità:",
  "di essere regolarmente iscritto/a presso l'Università di Pisa al Corso di Laurea sopra indicato;",
  "di essere in possesso dei requisiti di carriera accademica (CFU) richiesti per l’accesso e la permanenza nel Team;",
  "di possedere una competenza linguistica in inglese pari almeno al livello B2;",
  "di non trovarsi in situazioni di conflitto di interesse con gli scopi istituzionali del Team.",
  "4. Trattamento Dati Personali e Diritto all'Immagine (GDPR)",
  "Autorizza il Team Galileo e l’Università di Pisa al trattamento dei propri dati personali per finalità istituzionali. Presta altresì consenso gratuito e senza limiti temporali alla diffusione di materiale multimediale (foto, video) realizzato durante le attività ufficiali per scopi promozionali e divulgativi.",
];
